permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: mason
  email: mianshenglee@foxmail.com
  link: 
  weibo: http://weibo.com/mason32
  github: https://github.com/mianshenglee

# 站点信息
title: mason's blog
description: My personal blog
url: https://mianshenglee.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/cow.png
favicon: /public/img/cow.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: https://mianshenglee.github.io/

# disqus 设置
disqus:
  shortname: mason

# 主题设置，自动激活某个标签
active: IT

# 首页除了最新文章外显示分类
cates: 
  - Java
  - SpringBatch
  - book

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
